###
GET https://antstackmetalog.herokuapp.com/api/find-metatag
Content-Type: application/json

{
    "url": "https://www.flipkart.com",
    "metatag_name": "Keywords"
}

###
GET https://antstackmetalog.herokuapp.com/api/dns-lookup
Content-Type: application/json

{
    "url": "geeksforgeeks.org",
    "dns_txt": "A"
}